Freezing layer 'model.22.dfl.conv.weight'
[34m[1mAMP: [39m[22mrunning Automatic Mixed Precision (AMP) checks with YOLOv8n...
[34m[1mAMP: [39m[22mchecks passed ‚úÖ
WARNING ‚ö†Ô∏è updating to 'imgsz=640'. 'train' and 'val' imgsz must be an integer, while 'predict' and 'export' imgsz may be a [h, w] list or an integer, i.e. 'yolo export imgsz=640,480' or 'yolo export imgsz=640'
[34m[1mtrain: [39m[22mWARNING ‚ö†Ô∏è /home/jason/Desktop/datasets/car_dataset/train/images/2022-07-14-21-41-50.752.png: ignoring corrupt image/label: negative label values [  -0.090278    -0.15509]
[34m[1mtrain: [39m[22mWARNING ‚ö†Ô∏è /home/jason/Desktop/datasets/car_dataset/train/images/S504.png: ignoring corrupt image/label: negative label values [   -0.78191]
[34m[1mtrain: [39m[22mWARNING ‚ö†Ô∏è /home/jason/Desktop/datasets/car_dataset/train/images/S505.png: ignoring corrupt image/label: negative label values [   -0.55733    -0.48581]
[34m[1mtrain: [39m[22mWARNING ‚ö†Ô∏è /home/jason/Desktop/datasets/car_dataset/train/images/S514.png: ignoring corrupt image/label: negative label values [   -0.13202     -0.1909]
[34m[1mtrain: [39m[22mWARNING ‚ö†Ô∏è /home/jason/Desktop/datasets/car_dataset/train/images/S519.png: ignoring corrupt image/label: negative label values [   -0.63175]
[34m[1mtrain: [39m[22mWARNING ‚ö†Ô∏è /home/jason/Desktop/datasets/car_dataset/train/images/S522.png: ignoring corrupt image/label: negative label values [   -0.41528    -0.49444]
[34m[1mtrain: [39m[22mWARNING ‚ö†Ô∏è /home/jason/Desktop/datasets/car_dataset/train/images/S529.png: ignoring corrupt image/label: negative label values [   -0.52908    -0.25914]
WARNING ‚ö†Ô∏è No 'flip_idx' array defined in data.yaml, setting augmentation 'fliplr=0.0'
[34m[1mtrain: [39m[22mScanning /home/jason/Desktop/datasets/car_dataset/train/labels.cache... 3045 images, 2 backgrounds, 7 corrupt: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà
[34m[1mval: [39m[22mScanning /home/jason/Desktop/datasets/car_dataset/val/labels.cache... 1032 images, 0 backgrounds, 0 corrupt: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà
Plotting labels to /home/jason/Desktop/YOLO-Pruning-RKNN/runs/pose/train17/labels.jpg...
[34m[1moptimizer:[39m[22m 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
[34m[1moptimizer:[39m[22m SGD(lr=0.01, momentum=0.9) with parameter groups 63 weight(decay=0.0), 73 weight(decay=0.000625), 72 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to [1m/home/jason/Desktop/YOLO-Pruning-RKNN/runs/pose/train17
Starting training for 500 epochs...
      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/76 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/jason/Desktop/yolov8-test/train_yolov8_pose.py", line 8, in <module>
    results = model.train(data='cars-pose.yaml', epochs=500,device='0',
  File "/home/jason/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 668, in train
    self.trainer.train()
  File "/home/jason/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 198, in train
    self._do_train(world_size)
  File "/home/jason/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 370, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/jason/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jason/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jason/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 88, in forward
    return self.loss(x, *args, **kwargs)
  File "/home/jason/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 267, in loss
    return self.criterion(preds, batch)
  File "/home/jason/.local/lib/python3.10/site-packages/ultralytics/utils/loss.py", line 500, in __call__
    loss[1], loss[2] = self.calculate_keypoints_loss(
  File "/home/jason/.local/lib/python3.10/site-packages/ultralytics/utils/loss.py", line 581, in calculate_keypoints_loss
    kpts_loss = self.keypoint_loss(pred_kpt, gt_kpt, kpt_mask, area)  # pose loss
  File "/home/jason/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jason/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jason/.local/lib/python3.10/site-packages/ultralytics/utils/loss.py", line 140, in forward
    d = (pred_kpts[..., 0] - gt_kpts[..., 0]).pow(2) + (pred_kpts[..., 1] - gt_kpts[..., 1]).pow(2)
RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1